// Generated by CoffeeScript 1.12.4
(function() {
  module.exports = function() {
    this.initConfig({
      pkg: this.file.readJSON('package.json'),
      mochaTest: {
        nodejs: {
          src: ['spec/*.coffee'],
          options: {
            reporter: 'spec',
            timeout: 20000,
            require: 'coffee-script/register',
            grep: process.env.TESTS
          }
        }
      },
      coffeelint: {
        all: {
          files: {
            src: ['components/*.coffee', 'spec/*.coffee']
          },
          options: {
            max_line_length: {
              value: 80,
              level: 'ignore'
            }
          }
        }
      }
    });
    this.loadNpmTasks('grunt-mocha-test');
    this.loadNpmTasks('grunt-coffeelint');
    this.registerTask('test', ['coffeelint', 'mochaTest']);
    return this.registerTask('default', ['test']);
  };

}).call(this);
