// Generated by CoffeeScript 1.12.4
(function() {
  var noflo;

  noflo = require('noflo');

  exports.getComponent = function() {
    var c;
    c = new noflo.Component({
      description: 'Test using fbp-spec',
      inPorts: {
        "in": {
          datatype: 'array',
          description: 'data we want to send',
          required: true
        }
      },
      outPorts: {
        out: {
          datatype: 'string',
          description: 'the data wrapped in brackets',
          required: true
        }
      }
    });
    return c.process(function(input, output) {
      var data, datas, i, len;
      if (input.ip.type !== 'data') {
        return input.buffer.get().pop();
      }
      if (!input.has('in')) {
        return;
      }
      output.send({
        out: new noflo.IP('openBracket')
      });
      datas = input.getData('in');
      if (!Array.isArray(datas)) {
        datas = [datas];
      }
      for (i = 0, len = datas.length; i < len; i++) {
        data = datas[i];
        output.send({
          out: new noflo.IP('data', data)
        });
      }
      output.send({
        out: new noflo.IP('closeBracket')
      });
      output.send({
        out: new noflo.IP('closeBracket')
      });
      return output.done();
    });
  };

}).call(this);
